<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php if ($this->helper('itactica_layerednavigation')->isPriceSliderEnabled()): ?>
    <div id="price-range" class="filter-track price-slider">
        <span id="price-min" class="filter-handle price-slider-from" title="Scroll to set your minimum value"></span>
        <span id="price-max" class="filter-handle price-slider-to" title="Scroll to set your maximum value"></span>
    </div>
    <ul class="price-display clearfix">
        <li>
            <span id="price-min-display"><?php echo $this->getCurrencySymbol(); ?><?php echo $this->getCurrentMinPriceFilter(); ?></span>
            <span style="float: right;" id="price-max-display"><?php echo $this->getCurrencySymbol(); ?><?php echo $this->getCurrentMaxPriceFilter(); ?></span>
        </li>
    </ul>
    <?php if ($this->isSubmitTypeButton()): ?>
    <div class="a-right">
        <button id="button-price-slider" class="button tiny" onclick="handlePriceEvent(this.value)" value=""><span><span><?php echo $this->__('Update') ?></span></span></button>
    </div>
    <?php endif; ?>

    <script type="text/javascript">
        priceSliderUrlTemplate = '<?php echo $this->getUrlPattern(); ?>';
        
        <?php if (!$this->getRequest()->isAjax()): ?>
        function handlePriceEvent(val) {
            if (val) {
                var url = priceSliderUrlTemplate.replace('__PRICE_VALUE__', val);
                <?php if ($this->helper('itactica_layerednavigation')->isAjaxEnabled()): ?>
                handleEvent(url);
                <?php else: ?>
                window.location.href = url;    
                <?php endif; ?>
            }
        }
        <?php endif; ?>
        
        maxPriceInt = <?php echo $this->getMaxPriceFloat(); ?>;
        minPriceInt = <?php echo $this->getMinPriceFloat(); ?>;
        currencySymbol = "<?php echo $this->getCurrencySymbol(); ?>";
        <?php if (!$this->isSubmitTypeButton()): ?>
        timerSlider = null;
        priceSliderDelay = <?php echo $this->helper('itactica_layerednavigation')->getPriceSliderDelay() * 1000 ?>;
        <?php endif; ?>

        // horizontal slider control with preset values
        function initSlider() {
        setTimeout(function() {
            new Control.Slider(['price-min', 'price-max'], 'price-range', {
                range: $R(minPriceInt, maxPriceInt),
                sliderValue: [<?php echo $this->getCurrentMinPriceFilter(); ?>, <?php echo $this->getCurrentMaxPriceFilter(); ?>],
                values: $R(minPriceInt, maxPriceInt),
                restricted: true,
                onChange: function(val){
                    if (val[0] != <?php echo $this->getCurrentMinPriceFilter(); ?> || val[1] != <?php echo $this->getCurrentMaxPriceFilter(); ?>) {
                        <?php if ($this->isSubmitTypeButton()): ?>
                            $('button-price-slider').value = val.join('-');
                        <?php else: ?>
                            if (timerSlider) {
                                clearTimeout(timerSlider);
                            }
                            val[1] = val[1] + 0.01;
                            timerSlider = setTimeout(handlePriceEvent, priceSliderDelay, val.join('-'));
                        <?php endif; ?>
                    }
                },
                onSlide: function(val){ 
                    $('price-max-display').innerHTML = currencySymbol+val[1];
                    $('price-min-display').innerHTML = currencySymbol+val[0];
                }
            });
        }, 500);
        }
        initSlider();
        document.observe("dom:loaded", function() {
            initSlider();
        });
    </script>
<?php else: ?>
    <ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li<?php if ($_item->isPriceRangeSelected($_item->getLabel())): ?> class="checked"<?php endif; ?>>
            <?php if ($_item->getCount() > 0): ?>
            <a href="<?php echo ($_item->isPriceRangeSelected($_item->getLabel())) ? $_item->getRemoveUrl() : $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?><?php if ($this->shouldDisplayProductCount()): ?><span> (<?php echo $_item->getCount() ?>)</span><?php endif; ?></a>
            <?php else: echo $_item->getLabel() ?><?php if ($this->shouldDisplayProductCount()): ?><span> (<?php echo $_item->getCount() ?>)</span><?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    </ol>
<?php endif; ?>