<?php
/**
 * Intenso Premium Theme
 *
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
class Itactica_Intenso_Helper_Data extends Mage_Core_Helper_Abstract
{
	/**
     * folder path for CSS files generated by config
     */
    const CSS_CONFIG_FOLDER		= 'css/config/';
    const CSS_CONFIG_PATH		= 'frontend/intenso/default/';
    const CSS_TEMPLATE_PATH		= 'itactica_intenso/css/';

	/**
     * get Google Fonts stylesheet link
     * @access public
     * @return string
     */
	public function getGoogleFontsScript() {
		$configFontFamily = Mage::getStoreConfig('intenso/fonts/font_family', 
			Mage::app()->getStore());

		$configGoogleFont = str_replace(' ', '+', Mage::getStoreConfig('intenso/fonts/google_fonts',
			Mage::app()->getStore()));
		
		$configFontSubset = Mage::getStoreConfig('intenso/fonts/font_subset',
			Mage::app()->getStore());

		$configFontStyles = Mage::getStoreConfig('intenso/fonts/font_styles',
			Mage::app()->getStore());

		if ($configFontStyles == 'regular') $configFontStyles = '400';
		if ($configFontStyles == 'italic') $configFontStyles = '400italic';

		if ($configFontFamily == 'google') {
			return '<link rel="stylesheet" href="//fonts.googleapis.com/css?family='.$configGoogleFont.':'.$configFontStyles.'&amp;subset='.$configFontSubset.'" />';
		}
	}

	/**
     * return number of columns in footer
     * @access public
     * @return array
     */
	public function mainFooterColumnCount() {
		$_count = 4;
		if (!Mage::getModel('cms/block')->load('footer_main_first_column')->getIsActive()) {
			$_count--;
		}
		if (!Mage::getModel('cms/block')->load('footer_main_second_column')->getIsActive()) {
			$_count--;
		}
		if (!Mage::getModel('cms/block')->load('footer_main_third_column')->getIsActive()) {
			$_count--;
		}
		if (!Mage::getModel('cms/block')->load('footer_main_fourth_column')->getIsActive()) {
			$_count--;
		}
		return $_count;
	}

	/**
     * whether to show or not the footer's top ribbon
     * @access public
     * @return boolean
     */
	public function showFooterRibbon() {
		if (Mage::getStoreConfig('intenso/footer/newsletter', Mage::app()->getStore())
			|| (Mage::getModel('cms/block')->load('footer_top_left')->getIsActive()
			|| Mage::getModel('cms/block')->load('footer_top_right')->getIsActive())) {
			return true;
		} else {
			return false;
		}
	}

	/**
     * file path and name of CSS settings file
     * @access public
     * @param string
     * @return string
     */
	public function getConfigCssFile($storeCode = NULL) {
		if ($storeCode) {
			return $this->getConfigCssPath() . self::CSS_CONFIG_FOLDER;
		} else {
			return self::CSS_CONFIG_FOLDER . 'settings-' . Mage::app()->getStore()->getCode() . '.css';
		}
	}

	/**
     * file path of CSS settings file
     * @access public
     * @return string
     */
	public function getConfigCssPath() {
		return Mage::getBaseDir('skin') . '/' . self::CSS_CONFIG_PATH;
	}

	/**
     * file path of CSS template file
     * @access public
     * @return string
     */
	public function getConfigCssTemplate() {
		return 'itactica_intenso' . DS . 'css' . DS;
	}

	/**
     * get current datetime
     * @access public
     * @return string
     */
	public function getDatetime() {
		$datetime = Zend_Date::now();
		$datetime->setLocale(Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_LOCALE))
		->setTimezone(Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE));
		return $datetime->get(Zend_Date::DATETIME_SHORT);
	}

	/**
     * get store's setup configuration
     * @access public
     * @param int
     * @return string
     */
	public function getStoreSetupConfig($storeId = NULL) {
		if ($storeId) {
			return Mage::getStoreConfig('intenso', $storeId);
		} else {
			return Mage::getStoreConfig('intenso');
		}
    }

	/**
     * get store's design configuration
     * @access public
     * @param int
     * @return string
     */
	public function getStoreDesignConfig($storeId = NULL) {
		if ($storeId) {
			return Mage::getStoreConfig('intenso_design', $storeId);
		} else {
			return Mage::getStoreConfig('intenso_design');
		}
    }

	/**
     * check whether configurable swatches is enabled (or exist in this version)
     * @access public
     * @return bool
     */
    public function isConfigSwatchesEnabled() {
    	 return Mage::getStoreConfig('configswatches/general/enabled', Mage::app()->getStore());
    }

    /**
     * get current configuration scope
     * @access public
     * @return int
     */
    public function getCurrentConfigScope() {
    	if (strlen($code = Mage::getSingleton('adminhtml/config_data')->getStore())) {
    		// store level
		    $storeId = Mage::getModel('core/store')->load($code)->getId();
		}
		elseif (strlen($code = Mage::getSingleton('adminhtml/config_data')->getWebsite())) {
		    // website level
		    $websiteId = Mage::getModel('core/website')->load($code)->getId();
		    $storeId = Mage::app()->getWebsite($websiteId)->getDefaultStore()->getId();
		}
		else // default level
		{
		    $storeId = 0;
		}

		return $storeId;
    }

    /**
     * get base64 image for star rating
     * @access public
     * @param string
     * @return string
     */
    public function getRatingBackgroundImage($color = 'turquoise') {
    	$ratingColors = array( 
			'turquoise' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iIzI3Q0NDMCIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiMyN0NDQzAiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjMjdDQ0MwIiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iIzI3Q0NDMCIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjMjdDQ0MwIiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==', 
			'yellow' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iI0Y5QkYzQiIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiNGOUJGM0IiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjRjlCRjNCIiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iI0Y5QkYzQiIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjRjlCRjNCIiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==', 
			'red' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iI0ZGMDAwMCIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiNGRjAwMDAiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjRkYwMDAwIiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iI0ZGMDAwMCIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjRkYwMDAwIiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==',
			'green' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iI0NDREIzOCIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiNDQ0RCMzgiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjQ0NEQjM4IiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iI0NDREIzOCIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjQ0NEQjM4IiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==',
			'blue' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iIzUyQjNEOSIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiM1MkIzRDkiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjNTJCM0Q5IiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iIzUyQjNEOSIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjNTJCM0Q5IiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==',
			'gray' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iIzZDN0E4OSIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiM2QzdBODkiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjNkM3QTg5IiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iIzZDN0E4OSIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjNkM3QTg5IiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==',
			'purple' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iIzkxM0Q4OCIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiM5MTNEODgiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjOTEzRDg4IiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iIzkxM0Q4OCIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjOTEzRDg4IiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg==',
			'pink' => 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjIwMHB4IiBoZWlnaHQ9IjM4LjE2N3B4IiB2aWV3Qm94PSIwIDAgMjAwIDM4LjE2NyIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjAwIDM4LjE2NyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggZmlsbD0iI0UwODI4MyIgZD0iTTE4LjUyLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEzLDEyLjc4OWMyLjYwNiwxLjk4MiwxMi40NC0xLjk1MywxMy40MzUsMS4yNTVjMC45OTUsMy4yMDgtOC45MTUsNS41MjMtOS45MSw4LjczNWMtMC45OTYsMy4yMDgsNS40NjksMTIuMDA0LDIuODYzLDEzLjk5Yy0yLjYwNiwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyMSwwLTguNzk4LDkuNjM1LTExLjQwMiw3LjY1M2MtMi42MDYtMS45ODYsMy44NTctMTAuNzgyLDIuODYzLTEzLjk5Yy0wLjk5NS0zLjIxMS0xMC45MDUtNS41MjYtOS45MS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1QzE2LjEwOSwxMS45MzcsMTUuMjk5LDEuMTI5LDE4LjUyLDEuMTI5eiIvPjxwYXRoIGZpbGw9IiNFMDgyODMiIGQ9Ik01OS4yNiwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDYsMS45ODIsMTIuNDQtMS45NTMsMTMuNDM1LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk3LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MywxMy45OWMtMi42MDYsMS45ODItOC4xODItNy42NTMtMTEuNC03LjY1M2MtMy4yMjEsMC04Ljc5OCw5LjYzNS0xMS40MDIsNy42NTNjLTIuNjA2LTEuOTg2LDMuODU3LTEwLjc4MiwyLjg2My0xMy45OWMtMC45OTUtMy4yMTEtMTAuOTA1LTUuNTI2LTkuOTExLTguNzM1YzAuOTk3LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzUtMS4yNTVDNTYuODUsMTEuOTM3LDU2LjAzOSwxLjEyOSw1OS4yNiwxLjEyOXoiLz48cGF0aCBmaWxsPSIjRTA4MjgzIiBkPSJNMTAwLDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDExLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM3LDEuMjU1YzAuOTk1LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2MSwxMy45OWMtMi42MDQsMS45ODItOC4xOC03LjY1My0xMS4zOTktNy42NTNjLTMuMjIxLDAtOC43OTgsOS42MzUtMTEuNDAyLDcuNjUzYy0yLjYwNS0xLjk4NiwzLjg1OC0xMC43ODIsMi44NjMtMTMuOTljLTAuOTk1LTMuMjExLTEwLjkwNS01LjUyNi05LjkxMS04LjczNWMwLjk5Ny0zLjIwOCwxMC44MjksMC43MjcsMTMuNDM1LTEuMjU1Qzk3LjU5LDExLjkzNyw5Ni43OCwxLjEyOSwxMDAsMS4xMjl6Ii8+PHBhdGggZmlsbD0iI0UwODI4MyIgZD0iTTE0MC43NCwxLjEyOWMzLjIxOSwwLDIuNDA5LDEwLjgwNyw1LjAxMywxMi43ODljMi42MDgsMS45ODIsMTIuNDQyLTEuOTUzLDEzLjQzNywxLjI1NWMwLjk5NCwzLjIwOC04LjkxNiw1LjUyMy05LjkxLDguNzM1Yy0wLjk5NSwzLjIwOCw1LjQ2OSwxMi4wMDQsMi44NiwxMy45OWMtMi42MDQsMS45ODItOC4xODEtNy42NTMtMTEuNC03LjY1M2MtMy4yMTksMC04Ljc5Nyw5LjYzNS0xMS40MDEsNy42NTNjLTIuNjA0LTEuOTg2LDMuODU1LTEwLjc4MiwyLjg2NS0xMy45OWMtMC45OTgtMy4yMTEtMTAuOTA4LTUuNTI2LTkuOTEtOC43MzVjMC45OTUtMy4yMDgsMTAuODI5LDAuNzI3LDEzLjQzMy0xLjI1NVMxMzcuNTIxLDEuMTI5LDE0MC43NCwxLjEyOXoiLz48cGF0aCBmaWxsPSIjRTA4MjgzIiBkPSJNMTgxLjQ4LDEuMTI5YzMuMjE5LDAsMi40MDksMTAuODA3LDUuMDEyLDEyLjc4OWMyLjYwOCwxLjk4MiwxMi40NDItMS45NTMsMTMuNDM4LDEuMjU1YzAuOTk0LDMuMjA4LTguOTE2LDUuNTIzLTkuOTEsOC43MzVjLTAuOTk1LDMuMjA4LDUuNDY5LDEyLjAwNCwyLjg2LDEzLjk5Yy0yLjYwNCwxLjk4Mi04LjE4MS03LjY1My0xMS40LTcuNjUzYy0zLjIyLDAtOC43OTcsOS42MzUtMTEuNDAxLDcuNjUzYy0yLjYwNC0xLjk4NiwzLjg1NS0xMC43ODIsMi44NjUtMTMuOTljLTAuOTk5LTMuMjExLTEwLjkwOS01LjUyNi05LjkxLTguNzM1YzAuOTk0LTMuMjA4LDEwLjgyOSwwLjcyNywxMy40MzMtMS4yNTVDMTc5LjA3MSwxMS45MzcsMTc4LjI2MSwxLjEyOSwxODEuNDgsMS4xMjl6Ii8+PC9nPjwvc3ZnPg=='
		);
		return $ratingColors[$color];
    }

    /**
     * get header additional info
     * @access public
     * @return string
     */
    public function getAdditionalInfo() {
    	return Mage::getStoreConfig('intenso/header/additional_info', Mage::app()->getStore());
    }

    /**
     * return true if secondary menu is active
     * @access public
     * @return boolean
     */
    public function showSecondaryMenu() {
    	return Mage::getStoreConfig('intenso/header/sec_menu', Mage::app()->getStore());
    }

    /**
     * return true if secondary menu is set to be a ribbon
     * @access public
     * @param int
     * @return boolean
     */
    public function secMenuTop($storeId = NULL) {
    	if ($storeId === NULL) {
    		$storeId = Mage::app()->getStore();
    	}
    	return Mage::getStoreConfig('intenso/header/sec_menu_style', $storeId);
    }

    /**
     * get order history url
     * @access public
     * @return string
     */
    public function getOrderHistoryUrl() {
        return Mage::getUrl('sales/order/history', array('_secure'=>true));
    }

    /**
     * ads # symbol to hexadecimal color code in case is not present
     * @access public
     * @param string
     * @return string
     */
    public function hex($color) {
    	if (substr($color, 0, 1) != '#') {
    		$color = '#' . $color;
    	}
        return $color;
    }

    /**
     * get image height
     * @access public
     * @param array|Varien_Data_Collection
     * @return int
     */
    public function getGalleryImagesHeight($galleryImages, $product, $width) {
        $height = array();
        $resizeAsSquare = array();
        $fixed = false;
        $i=1;
        foreach ($galleryImages as $image) {
            $_image = new Varien_Image($image->getPath());
            $originalWidth = $_image->getOriginalWidth();
            $originalHeight = $_image->getOriginalHeight();
            $resizeAsSquare[$i] = max($originalWidth, $originalHeight);
            $heightRatio = $originalWidth / $originalHeight;
            $height[$i] = round($width / $heightRatio);
            $i++; 
        }
        $maxHeight = Mage::getStoreConfig('intenso/product_page/image_fixed_height', Mage::app()->getStore());
        if (Mage::getStoreConfig('intenso/product_page/keep_image_aspect_ratio', Mage::app()->getStore()) && !empty($height)) {
        	$maxHeight = max($height);
        }
	    // get proportions for base image
	    $baseImage = Mage::helper('catalog/image')->init($product, 'image');
	    $originalWidth = $baseImage->getOriginalWidth();
    	$originalHeight = $baseImage->getOriginalHeight();
    	unset($baseImage);
    	$baseImageSize = max($originalWidth, $originalHeight);

        return array($maxHeight,$resizeAsSquare,$baseImageSize);
    }

    /**
     * generates a classname from store code and locale
     * can be used in CSS to target specific store views
     * @access public
     * @param string
     * @return string
     */
    public function getStoreClass() {
    	$locale = strtolower(Mage::app()->getLocale()->getLocaleCode());
		$storeCode = strtolower(Mage::app()->getStore()->getCode());
        return ' ' . $storeCode . ' ' . $locale;
    }

    /**
     * adds a classname to body tag to allow applying different styles to form fields
     * @access public
     * @return string
     */
    public function formFieldsType() {
    	return Mage::getStoreConfig('intenso_design/page/form_fields_style', Mage::app()->getStore());
    }

    /**
     * return true if Company field must be enabled in checkout
     * @access public
     * @return bool
     */
    public function useCompanyField() {
		return Mage::getStoreConfig('intenso/checkout/company_field', 
			Mage::app()->getStore());
	}

	/**
     * calculate padding-top for catalog images
     * @access public
     * @return bool
     */
    public function getPictureStyle() {
    	if (Mage::getStoreConfig('intenso/catalog/keep_image_aspect_ratio', Mage::app()->getStore()) == false) {
			$paddingTopRatio = 0.232549504950495;
	        $paddingTopPercentage = $paddingTopRatio * Mage::getStoreConfig('intenso/catalog/catalog_product_height', Mage::app()->getStore());
	        return 'style="padding-top: ' . $paddingTopPercentage . '%;"';
	    }
	}

	/**
     * check if keep aspect ratio is enabled
     *
     * @access public
     * @return bool
     */
    public function isKeepAspectRatio() {
        if (Mage::getStoreConfig('intenso/catalog/keep_image_aspect_ratio', Mage::app()->getStore())) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * get image height
     * @access public
     * @param Varien_Data_Collection
     * @param int
     * @param int
     * @return int
     */
    public function getImageHeight($product, $width = 430, $height = 404) {
        if (Mage::getStoreConfig('intenso/catalog/keep_image_aspect_ratio', Mage::app()->getStore())) {
            // get proportions for base image
            $image = Mage::helper('catalog/image')->init($product, 'small_image');
            $originalWidth = $image->getOriginalWidth();
            $originalHeight = $image->getOriginalHeight();
            unset($image);
            $heightRatio = $originalWidth / $originalHeight;
            $height = round($width / $heightRatio);
        } else {
            return $height;
        }
        return $height;
    }

    /**
     * get image padding setting from config
     * @access public
     * @return bool
     */
    public function isFlushed() {
        if (Mage::getStoreConfig('intenso/catalog/remove_image_padding', Mage::app()->getStore())) {
            return true;
        } else {
            return false;
        }
    }

}