<?php
$helper = $this->helper('escommon');
?>
<?php
if ($helper->isJqueryEnabled()):
    ?>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write(unescape('%3Cscript src="<?php echo $helper->getJqueryFallbackSrc() ?>"%3E%3C/script%3E'))</script>
<?php
endif;

if ($helper->isFontAwesomeEnabled()):
?>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<?php endif; ?>
<script type="text/javascript">$es = jQuery.noConflict();</script>
<?php if ($helper->isUserEmailSet()):?>
    <!-- ESHIFT_ID: <?php echo $helper->getUserHash() ?> -->
<?php endif; ?>
<?php echo $this->getChildHtml('es_head_add') ?>