<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>

<?php $_product = Mage::registry('product'); ?>
    <a class="button secondary small" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Back to Main Product Info') ?></a>
